name: test
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
 
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  flutter:
    sdk: flutter
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\logo.png
    - assets\appbar-background.jpg
    - assets/adventure/adams_peak.webp
    - assets/adventure/walking_in_the_hills.jpg
    - assets\adventure\jeep_safari.jpg
    - assets\adventure\jet_sking.jpg
    - assets\adventure\kite_surfing.webp
    - assets\adventure\lagoon_safari.jpg
    - assets\adventure\learn_to_surf.jpg
    - assets\adventure\pekoe_trail.jpg
    - assets\adventure\rock_climbing.jpg
    - assets\adventure\scuba_diving.jpg
    - assets\adventure\train_through_the_hill.jpg
    - assets\adventure\white_water_rafting.jpg
    - assets\appbar-background.jpg
    - assets\cargills-food-city.jpg
    - assets\coolplanet.jpeg
    - assets\ext.jpg
    - assets\spar.jpeg
    - assets\perera&sons.jpeg
    - assets\ipharma.jpeg
    - assets\learningpoints\geographynlocation.jpg
    - assets\learningpoints\historynculture.jpg
    - assets\learningpoints\naturenwildlife.jpg
    - assets/groups/1.png
    - assets/groups/2.png
    - assets/groups/3.png
    - assets/groups/4.png
    - assets/groups/5.png
    - assets/groups/6.png
    - assets/groups/7.png
    - assets/groups/8.jpg
    - assets/groups/9.png
    - assets/groups/
    - assets/background.png
    - assets/image01.jpeg
    - assets/image02.jpg
    - assets/image03.png
    - assets/logo.png
    - assets/pic01.png
    - assets/pic03.png
    - assets/pic04.png
    - assets/pic02.png
    - assets/background01.png
    - assets/1990.png
    - assets/bell.png
    - assets/image04.png
    - assets/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
