name: test
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^10.0.0
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/image01.jpeg
    - assets/image02.jpg
    - assets/image03.png
    - assets/logo.png
    - assets/pic01.png
    - assets/pic03.png
    - assets/pic04.png
    - assets/pic02.png
    - assets/background01.png
    - assets/1990.png
    - assets/bell.png
    - assets/image04.png
    - assets/logo.png
    - assets/emergency_bell.png
    - assets/taxi.png
    - assets/maid.png
    - assets/auto.png
    - assets/print.png
    - assets/profile.jpg
    - assets/appname.png